### ISSUE TITLE
Bibliography at end of chapter

### ISSUE THREAD

**Issue by mattialopresti** [joaomlourenco/novathesis#121]
Hello, I'm facing an issue that I'm not able to solve alone. Due to the rules in my university, I have to print bibliography at the end of each chapter, also resetting the numbering everytime. Also, in each bibliography, including the whole one at the end of the thesis, must appear only cited works and in order of apparition with progressive numbers.
I put at the end of each chapter this string:

`% Print chapter bibliography only
\printbibliography[heading=subbibliography, segment=\therefsegment, title={\bibname\ for chapter~\thechapter}]`

While in the novathesis.cls file the code is:

\newcommand{\@ntaddlisthookfilebib}[2]{%
  \letoptionlist{/novathesis/biblatex}\nt@tmp%
  \typeout{'NT PASSING TO BIBLATEX= '\nt@tmp}%
\RequirePackage[refsegment=chapter,hyperref=true,\nt@tmp]{biblatex}%
  \DeclareLanguageMapping{english}{american-apa}%
  \DeclareLanguageMapping{italian}{italian-apa}%
  \setcounter{biburlnumpenalty}{100}% Allow to break DOIs in bibliography
  \typeout{'NT ADD BIBLATEX RESOURCE= '#2}%
  \addbibresource{#2}%
}

\newcommand{\ntprintbib}{%
  \printbibliography%
}

The result is the following:
![Cattura](https://user-images.githubusercontent.com/32075052/101005996-4cb59300-3561-11eb-878c-d98acd97bd00.PNG)
![Cattura1](https://user-images.githubusercontent.com/32075052/101006006-4d4e2980-3561-11eb-9dda-67b94b7dfe7a.PNG)

Also, reference 2 is missing because it's formally in the glossary, but this obviously changes the enumeration.

**Comment by joaomlourenco** [comment]
Hi,

Thank you for using NOVAthesis.  If you need help adapting the template to your School let me know.  Also, if you don't mind sharing your definitions for your school, I would appreciate.

You wrote lots of information.  Can you please be more specific / clear.  ;)

What I understood:
1. you need to print bibliography per chapter with sequential numbering by order of appearance.
2. you need a global bibliography as well.
3. you have a problem with ref [2] because it is cited in glossary and not in the main text.

What I'm missing:
1. what is working?
2. where do you need help?
3. how are references numbered in the final bibliography if their numbering is reset in each chapter?

**Comment by mattialopresti** [comment]
For my institution there are no definitions (sadly). 
What you understood is correct, now for what you are missing:

1. I'm using the last release, the one of yesterday evening (5.1.5).
2. Bibliography correctly appears at the end of each chapter. Still, not in order of apparition and with a progressive numbering.
3. I need help in making something like it's reported in this answer on S.E. [https://tex.stackexchange.com/a/483310](url). As you can see, each chapter has its bibliography and an overall one is compiled at the end of the document.  I'd do this by myself, but I can't due to inexperience and because of the structure of the bibliography you made in the novathesis.cls file that I previouly quoted. 

Hope I explained myself better than before.

**Comment by joaomlourenco** [comment]
You should not change the "internals" of the template.  If you do, you will have hard time updating the template with new versions (with bugfixes).


With the With the following recommendations you will get:
- numbered bibliography per chapter sorted by order of appearance, restarting each chapter
- final bibliography with all the entries in the bib file(s) you added, sorted alphabetically

1. Update to the latest version (5.1.6) from GitHub

2. Keep the 

`\printbibliography[heading=subbibliography, segment=\therefsegment, title={\bibname\ for chapter~\thechapter}]`

at the end of each chapter.

3. Then edit "template.tex" to:

3.1. Declare the language mapping after the last "\ntaddfile{bib}{file}"

```
%%------------------------------------------------------------
% BibTeX bibiography files. Can be used multiple times with a single file nae each time.
% syntax:  \ntaddfile{bib}{filename.bib}
\ntaddfile{bib}{bibliography.bib}
\DeclareLanguageMapping{italian}{italian-apa}%
```

3.2. Add the appropriate options to the bibliography.  Please note the "refsection=chapter" and not "refsegment=chapter", so that the numbering is properly restarted in each chapter.

```
%%------------------------------------------------------------
%% NUMBERED ORDER BY CITATION
\ntbibsetup{refsection=chapter,style=numeric-comp, sortcites=true, sorting=none}
```

3.3. Create a file named "chapter-thebib.tex" with the following three lines

```
\newrefsection
\newrefcontext[sorting=nty]
\nocite{*}
```

and then add it as the last chapter…

```
%%------------------------------------------------------------
% Text chapters
% syntax: \ntaddfile{chapter}{filename}
\ntaddfile{chapter}{chapter1}
\ntaddfile{chapter}{chapter2}
\ntaddfile{chapter}{chapter3}
\ntaddfile{chapter}{chapter4}
\ntaddfile{chapter}{chapter-thebib}
```

**Comment by mattialopresti** [comment]
Thank you very much.
