### ISSUE TITLE
Uminho Formatting Standards

### ISSUE THREAD

**Issue by antoniosilva9116** [joaomlourenco/novathesis#149]
According to RT-31/2019, there are some standards that this repository does not meet:
(1) Copyright, Statement of Integrity and Dedicatory must have page numbering;
(2) The Abstract must have the title of the thesis;
(3) Abstract in Portuguese must always come first, even in English thesis;

**Comment by joaomlourenco** [comment]
António. 
Thanks for the notification.  
May I ask you to share RT-31/2019 with me?  And maybe other documentation/rules/… you may have?!  Thanks.

**Comment by antoniosilva9116** [comment]
Hello @joaomlourenco! Could you tell me what files I need to change to resolve the issues mentioned?

**Comment by joaomlourenco** [comment]
Support for uminho was added [in a fork](https://github.com/b-pereira/novathesis) of this project by Bruno Pereira (@b-pereira).

This project does not support uminho yet (although I plan to add the support asap).  Including the support from @b-pereira fork in the main repository is not trivial because Bruno worked on version 4.x and the main repo is in version 5.x now (with huge chances from v4.x)

Some hints to solve the problems:
1. open `novathesis.cls`, search where those pages are printed and and look for ´\thispagestyle{empty}` nearby.  Comment this command and the page number will appear (but it will have other implications as well).
2. This one is harder to solve.  It is solved in v5.x (which does not support uminho yet…) and would be not trivial to change v4.x to do this.
3. In the customization area of `template.tex` add:  `\abstractorder[en]={pt,en}`.

**Comment by antoniosilva9116** [comment]
Thank you @joaomlourenco for your help.

**Comment by b-pereira** [comment]
@antoniosilva9116 thank you for noticing the abstract order! I will add that to the fork.

By the way, there are other elements that aren't compliant with the RT-31/2019

> Tables, charts, graphs, figures, etc. they must be numbered, in each case, from 1 to N, and contain a synthetic title that clearly reflects the respective content;

In a separate custom template (nothing to do with _novathesis_ template), I managed to change the behavior of chapter/section numbering, i.e., 1.1, 2.3, etc, do 1 ... N. In this template I tried but I couldn't manage to do it. @joaomlourenco any thoughts on this?

Also, there are other elements that aren't compliant: the front page logos, other cover front page related formatting, as well, as you mentioned, the title must be in the abstract. 

Another considerations, from the Minho University's Professors, is that there's a difference between the title "Acronyms" and "Acronyms and Initialisms". That consideration was in the context of a Portuguese written dissertation in the Computer Networks area and the mention was for "Siglas e Acrónimos". My colleague had to change that because the _babel_ translation for "Acronyms" is "Siglas", which is not semantically correct. Also, @joaomlourenco what is your stand on this?

**Comment by joaomlourenco** [comment]
@b-pereira  @antoniosilva9116 

1) The sequential numbering of figures and tables is easy (according to Memoir manual), just have to add:
```\counterwithout{figure}{chapter}
\counterwithout{table}{chapter}```
after the `\mainmatter` command.

2) Not sure what Bruno is talking about on _ other elements aren't compliant_…

3) I am confused!  What is the problem?  The translation of "Acronyms"?  What should it be?  Or is it something else?

**Comment by antoniosilva9116** [comment]
So, in novathesis.cls we need to change the following: 

\newcommand{\thesismainmatter}{%
  % enables protrusion locally for the remainder of the document
  %\microtypesetup{protrusion=true} %
	\mainmatter%
	\counterwithout{table}{chapter} -> the line that you mentioned
	\pagenumbering{arabic} %
	\setlength{\headheight}{15pt}%
}

Am I wrong?

**Comment by joaomlourenco** [comment]
I would simply go to template.tex, look for 
```latex
\thesismainmatter  % The main text
```
and make it
```latex
\thesismainmatter  % The main text
\counterwithout{figure}{chapter}
\counterwithout{table}{chapter}
```

**Comment by b-pereira** [comment]
@joaomlourenco the other elements non 100% compliant are the cover and frontpage. 

1. I specified the metrics between logo, title, author name, project type, advisers as well as I could.<sup><a href="#foot1">[1]</a></sup> However, the metrics aren't the best match, at least the distance between the title and the type of work, because the title can have more lines than one. Given that I can't guess how many lines title will have, I let the \vfill specification that it's used with integer numbers. 
2. The front page school logo isn't the grey colour specified and doesn't have the skip between the university logo and school logo. The Informatics Department published a [PDF with forms](https://mei.di.uminho.pt/sites/default/files/Capa-MIMEI.pdf) where you can see how the cover should be.



<a id="foot1">[1]: </a>What I have been told is that there's a differentiation in the rigour between the printed cover/frontpage and the digital ones. At least, the Informatics Department don't stress the digital version to be _as exactly_ as requested. However, the printed version has to have the spine, back/front covers and front page _exactly_ as requested.  For that effect, the University made available those elements in Adobe Illustrator files at the Student Portal.

**Comment by b-pereira** [comment]
@joaomlourenco about the translation of "Acronyms", some Profs were more rigorous in the meaning of the translation. When my colleague sent the PDF with "Siglas" they recommend him to change to "Acrónimos" given that what he had were "acrónimos" and not "siglas". For instance, 6LowPAN is an acronym, whereas IBM is an initialism. That's why I asked your opinion: other Profs don't mind, at least that I what I observed.

**Comment by joaomlourenco** [comment]
@b-pereira Se virmos no site da Priberam (que é credível):
[(https://dicionario.priberam.org/inicialismo)](https://dicionario.priberam.org/inicialismo), a palavra “_inicialismo_” não aparece no dicionário, pelo que deve ser tido como um estrangeirismo importado do inglês.

Por outro lado, se virmos este outro site também credível:
[https://www.flip.pt/Duvidas-Linguisticas/Duvida-Linguistica/DID/1570](https://www.flip.pt/Duvidas-Linguisticas/Duvida-Linguistica/DID/1570), confirma-se que a tradução correta é mesmo “_Siglas e Acrónimos_”.  :)

**Comment by joaomlourenco** [comment]
@b-pereira  Relativamente ao suporte da UMinho, eu penso que o melhor era tiramos ambos uma tarde, abrirmos uma sessão Zoom, e fazermos isso em conjunto diretamente na nova versão do template.  O que dizes?

**Comment by b-pereira** [comment]
> Support for uminho was added [in a fork](https://github.com/b-pereira/novathesis) of this project by Bruno Pereira (@b-pereira).
> 
> This project does not support uminho yet (although I plan to add the support asap). Including the support from @b-pereira fork in the main repository is not trivial because Bruno worked on version 4.x and the main repo is in version 5.x now (with huge chances from v4.x).
> 
> Some hints to solve the problems:
> 
>     1. open `novathesis.cls`, search where those pages are printed and and look for ´\thispagestyle{empty}` nearby.  Comment this command and the page number will appear (but it will have other implications as well).
> 
>     2. This one is harder to solve.  It is solved in v5.x (which does not support uminho yet…) and would be not trivial to change v4.x to do this.
> 
>     3. In the customization area of `template.tex` add:  `\abstractorder[en]={pt,en}`.
> 
> 
> Maybe you want to contact @b-prereira and ask him to help you?!

For the page numbering, `\thispagestyle{plain}` in some places is what's necessary. Commenting out the `\thispagestyle{empty}` line will produce the header as well. In the `novathesis.cls` I'm doing some silly stuff, like using `\thispagestyle{empty}`  where it isn't supposed to, but some minimal changes can be done with no side effects. For some reason that I can't quite recall why I did, I declared the cover page before the front matter. To fix this problem in the `main.tex`:
```tex
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\thesisfrontmatter  % Before the main text (TOC, etc)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\printcoverpage    % The cover page
\setcounter{page}{2}
\printaftercover
\printcopyright    % Print the copyright page 
```
The `\setcounter{page}{2}` is to reset the page counter, after the front page, given that the front page must be "counted but pagination not shown" as in RT-31/2019

In `novathesis.cls` find `\thispagestyle{empty}` in:

```tex
\newcommand{\printcopyrightpage}{%
```
and 

```tex
\newcommand{\printstatementofintegritypage}{%
```
as well 
```tex
\def\dedicatory{%%
```
and 

```tex
\def\quote{%%
```
and change `\thispagestyle{empty}` to `\thispagestyle{plain}`

**Comment by b-pereira** [comment]
> @b-pereira Relativamente ao suporte da UMinho, eu penso que o melhor era tiramos ambos uma tarde, abrirmos uma sessão Zoom, e fazermos isso em conjunto diretamente na nova versão do template. O que dizes?

@joaomlourenco neste preciso momento há a entrega do relatório preliminar de dissertação e apresentação para a semana. Depois digo-lhe algo.

**Comment by b-pereira** [comment]
> I would simply go to template.tex, look for
> 
> ```
> \thesismainmatter  % The main text
> ```
> 
> and make it
> 
> ```
> \thesismainmatter  % The main text
> \counterwithout{figure}{chapter}
> \counterwithout{table}{chapter}
> ```

to be complete as possible:
```tex
\thesismainmatter  % The main text
\counterwithout{figure}{chapter}
\counterwithout{table}{chapter}
\counterwithout{equation}{chapter}
\counterwithout{algorithm}{chapter}
\counterwithout{lstlisting}{chapter}
```

**Comment by joaomlourenco** [comment]
Support for UMinho is available in the master version of he repository.
Just edit "Config/1_novathesis" and uncomment "\ntsetup{school=uminho/ee}".
To make a MSc dissertation, uncomment "\ntsetup{docdegree=msc}" in the same file.

Please report any problem you may by creating an new issue.  Thanks.

**Comment by DanielaOliveira-algoritmi** [comment]
Hi.

How can I configure the spine?

Thank you!!!!

**Comment by b-pereira** [comment]
@DanielaOliveira-algoritmi **this issue was closed. In the future, try to use the Discussions, namely the Q&A section, to ask your questions**, because I'll have to reopen the issue to close it again, just to answer you. Regarding your question, to make the spine you have to configure the file `Config/1_novathesis.tex` and find this snippet of code:

```latex
 %\ntsetup{spine=true}          % Shall a “book spine” be printed at the end of
 %                                           % the document?
 %                                           % DEFAULT: spine=false
```
then uncomment it

```latex
\ntsetup{spine=true}       
```
On the last page of the document this will appear:
![imagem](https://user-images.githubusercontent.com/944511/141838751-187e44cd-0e74-4239-9056-afc413008e4d.png)

**As a last remark** many colleagues from UMINHO even asked to remove the back cover from the document and didn't really care about the spine. **So they delivered the thesis or dissertation _without those elements_** (on the thesis side, I'm not so sure). Also, because of this strange behaviour of acceptance, I checked other theses and dissertations from RepositoriUM, and found out that many didn't have those elements, and others added the full cover (back + spine + front concatenated into a full cover) in the front of the document. In the end, if you're doing a doctoral thesis, and you'll have to print it, the stationary stores near _campi_ already have the official _Adobe Illustrator_ file and it is based on that, that your thesis cover will be printed. **For the record you were the first to ask! _Anyway, rules are rules!_** I think that @joaomlourenco has a method to put the full cover, but I **think** it isn't necessary. But if you want it, ask in the Discussions, under the Q&A.
