### ISSUE TITLE
[FEATURE REQ] Using Biber and not BibTeX

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/novathesis#249]
Make it clear in the template text itself, in the README, and in the wiki, that the NOVAthesis template depends on Biber for generating the bibliography (and not BibTeX).  Also recommend to use `latexmk` instead of pdflatex->biber->pdflatex->pdflatex (which sometimes is not enough and yet another pdflatex is necessary).

**Comment by snovaisg** [comment]
Could you write a minimum working solution on how to make biber work on novathesis' template on visual studio's tex workshop? I have tried some proposed solutions [1][2] but running both new recipes run into the same problem of not being able to recognize any references nor citations

[1] [solution 1](https://tex.stackexchange.com/a/459933/250209)
[2] [solution 2](https://tex.stackexchange.com/a/455652/250209)

**Comment by snovaisg** [comment]
Update

using the code from [here]("latex-workshop.latex.tools") and copying their `latex-workshop.latex.tools` and `latex-workshop.latex.recipes`attributes completely, the build command finally worked with `backend=biber`!

 Not sure what exactly made it work since it's a long code. I tried their `latexmk` recipe first, which failed the same way as the previous attempts, but the default build works.

**Comment by joaomlourenco** [comment]
Try the "Answer" from this post:
https://tex.stackexchange.com/questions/526320/how-can-i-get-vscodes-latex-workshop-to-find-the-right-installation-of-tex
and let me know if it works for you.
