### ISSUE TITLE
[FEATURE REQ] Add support for “user defined” covers

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/novathesis#385]
Use the "\ntaddfile{cover}[X]{filename}" to add cover files.

- X=1 -> front cover
- X=2 -> second cover
- X=N -> back cover

**Comment by b-pereira** [comment]
A custom spine command would be great too.

**Comment by joaomlourenco** [comment]
The spine is more complex, because its width depends on the number of pages of the document.
But it makes some sense to add one.  I'll address this in the near future using the same philosophy.

**Comment by b-pereira** [comment]
> The spine is more complex, because its width depends on the number of pages of the document. But it makes some sense to add one. I'll address this in the near future using the same philosophy.

That's why I mentioned _custom_. The _professionals_ that do measure the width have many ways to achieve that: using formulas or outright making single signatures (A3 pages folded into 4 A4 sequential pages), glue binding them, and using a caliper to measure the width. That being said, I think that the concern of cover printing should be only for professionals. 

Notwithstanding, if the thesis author wants to give some leverage to the printing company, by adding a specific width, that width has to come from the pros. Formulas aren't _silver bullets_ and the printing companies have to have some margin to do as they please.

All this came from research and a "field trip" to printing companies near _campi_. Well, I didn't go there for that specific purpose, but I did ask a printing company. UMINHO covers **with spine** and **_cover verses_** **reflecting the same spine** — not _back covers, dear future reader_ (not you @joaomlourenco xD) — gave me some ideas. _Custom_ means custom. @joaomlourenco just make sure that custom covers — or pages even, if you consider it in the near future — are in the _wiki_. _Oh, the headache!!_ Best wishes!

**Comment by joaomlourenco** [comment]
Available in v7.0.0.
