### ISSUE TITLE
glossaries — gls expansion

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/novathesis#94]
In the most recent version of the template, the first usage of an acronym (\gls{acname}) is not expanded and just prints the acronym.  In the past it was working all right.

**Comment by joaomlourenco** [comment]
Just guessing, this error may have been introduced with the support for the list of symbols!

**Comment by nunocalaim** [comment]
For future reference:

One workaround that I found was to add \setabbreviationstyle{long-short} in the customization area in the preamble!

**Comment by joaomlourenco** [comment]
Nuno, thank you for your suggestion.  However it didn't work for me with a vanilla copy of the template downloaded from GitHub.

**Comment by petersaints** [comment]
@joaomlourenco I have also tested @nunocalaim's solution on my own document without success. However, after further investigation I think that I have been able to fix it.

The command \setabbreviationstyle{long-short} only applies to entries defined with \newabbreviation, but the template (and my own document) uses \newacronym entries instead. For it to apply to those you have to use: \setabbreviationstyle[acronym]{long-short}.

**Comment by flaviomartins** [comment]
Recently the glossaries-extra package got more opinionated about the handling of acronyms or abbreviations. All the following are quoted from the glossaries-extra-manual available at https://ftp.eq.uc.pt/software/TeX/macros/latex/contrib/glossaries-extra/glossaries-extra-manual.pdf
> The \newacronym command provided by the glossaries package is redefined by glossaries-extra to use \newabbreviation with the category set to acronym.

So acronyms are not expanded on first use because abbreviations are not expanded by default on first use. Know that you cannot use the regular \setacronymstyle command in the glossaries package:
> Note that \setacronymstyle is disabled by glossaries-extra. Use \setabbreviationstyle[acronym]{〈style-name〉}
>(...)
> (Note the need to set the acronym style using \setabbreviationstyle before \newacronym.
See Section 3 for further details.)

Therefore, it seems to me that to fix this regression we need to add the following:
> \setabbreviationstyle[acronym]{long-short}

Experienced users can follow the recommendations of glossaries-extra package author instead and start using \glsfmtshort or \glsfmtlong:
> Use commands like \glsfmtshort or \glsfmtlong in section headings or captions instead of \gls. If you don’t want the full form to show on first use of \gls use one of the “nolong” or “noshort” styles.
